### ISSUE TITLE
Showing installed includes installed files

### ISSUE THREAD

**Issue by pbrisbin** [pbrisbin/wat#3]
Just noticed [this](https://github.com/pbrisbin/wat/blob/master/test/wat.t#L310)

/cc @jnwatts -- just as an FYI, not because I expect you to fix it or anything.

**Comment by jnwatts** [comment]
Ah, yeah: I noticed a similar "issue" w/ "upgrade" on my own system last night. I don't have access to the logs at the moment, but it was an installation comment that happened to have the word "upgrade" in it.

I had some thoughts on how to fix it last night, but forgot to look further into it (half-time show distracted me ;-)

See #4
